packages:
  - "examples/*"
  - "plugins/**"
  - "src"
  - "docs"

onlyBuiltDependencies:
  - "@biomejs/biome"

catalog:
  "typescript": "^5.3"
  "viem": "~2.29"
  "react": "^18.3"
  "react-dom": "^18.3"
  "@types/react": "^18.3"
  "@types/react-dom": "^18.3"
  "wagmi": "~2.15"
  "@wagmi/core": "~2.17"
  "@tanstack/react-query": "~5.74"
  "@dynamic-labs/types": "~4.18.3"
