packages:
  - "examples/*"
  - "plugins/**"
  - "src"
  - "docs"

onlyBuiltDependencies:
  - "@biomejs/biome"

catalog:
  "typescript": "^5.3"
  "viem": "^2.28"
  "react": "^18.2"
  "react-dom": "^18.2"
  "@types/react": "^18"
  "@types/react-dom": "^18"
  "wagmi": "^2.15"
  "@wagmi/core": "^2.17"
  "@tanstack/react-query": "^5.74"
