packages:
  - 'examples/*'
  - 'packages/*'
  - docs

onlyBuiltDependencies:
  - '@biomejs/biome'

catalog:
  "typescript": "^5.3.3"
  "viem": "^2.28.0"
  "react": "18.2.0"
  "react-dom": "18.2.0"
  "@types/react": "^18"
  "@types/react-dom": "^18"