packages:
  - examples/*
  - plugins/**
  - src
  - docs

catalog:
  '@dynamic-labs/types': ~4.29.4
  '@tanstack/react-query': ~5.85.5
  '@types/react': ^18.3.1
  '@types/react-dom': ^18.3.1
  '@wagmi/core': ~2.20.1
  react: ^18.3.1
  react-dom: ^18.3.1
  typescript: ^5.9.2
  viem: ~2.36.0
  wagmi: ~2.16.8

onlyBuiltDependencies:
  - '@biomejs/biome'
