packages:
  - examples/*
  - plugins/**
  - src
  - docs

catalog:
  typescript: ^5.9.2
  viem: ~2.35.1
  react: ^18.3.1
  react-dom: ^18.3.1
  '@types/react': ^18.3.1
  '@types/react-dom': ^18.3.1
  wagmi: ~2.16.6
  '@wagmi/core': ~2.20.1
  '@tanstack/react-query': ~5.85.5
  '@dynamic-labs/types': ~4.29.4

onlyBuiltDependencies:
  - '@biomejs/biome'
