packages:
  - 'examples/*'
  - 'packages/*'
  - docs

onlyBuiltDependencies:
  - '@biomejs/biome'

catalog:
  "typescript": "^5.3.3"
  "viem": "^2.28.0"
  "react": "^19.1.0"
  "@types/react": "^19.1.2"